[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/simple-server"
  status = 200

[dev]
  command = "npm run dev"
  functions = "netlify/functions" 