[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

# Clear cache for functions
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add function-specific settings
[functions]
  node_bundler = "esbuild" 